### ISSUE TITLE
Host receives an email once a position is created

### ISSUE THREAD

**Issue by heathermleroy** [rylero/JobCamp#36]
It would be nice to send a confirmation email to the host once a position is created.  It's fine to send a separate email for each position created, since most hosts only have 1.

Email sender: no-reply@jobcamp.org
Email subject:  JobCamp Position created for March 10, 2025
Email body:
Hi,
Thank you for participating in Los Gatos High School's JobCamp day on March 10, 2025.  You have created a new position that will be shared with students.  

Show the position information.

Can we add an "Edit" button that will take the user to the jobcamp.org site to edit this position (after a login, if necessary).

Note:  Your personal name, email, and phone number will NOT be shared with students at this time.  Immediately preceding JobCamp day, students will receive your information to reach out with an introductory email and to confirm their attendance.

Please let us know if you have any questions.
Regards,
JobCamp Team
admin@jobcamp.org

**Comment by rylero** [comment]
Mostly done. Right now the position information is only title, slots, and summary, but if you want to show more you just need to edit the template. should be pretty simple
